services:

  mongodb:
    image: mongo:7
    container_name: activity-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  activity-service:
    build: ./activityservice
    container_name: activity-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

volumes:
  mongo-data: