apiVersion: v1
kind: Service
metadata:
  name: lab-service
  namespace: mls-lab
spec:
  selector:
    app: lab-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
  namespace: mls-lab
  labels:
    app: lab-service
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: lab-config
      containers:
        - name: lab-service
          image: cohad-lab-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]

          env:
            # Secret (V7)
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: API_KEY

            # ✅ DB creds come from Secret and are referenced by application.properties
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-secrets
                  key: POSTGRES_PASSWORD

            # Profile & external config
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: lab-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"

          volumeMounts:
            - name: config-volume
              mountPath: /config

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
