apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: mls-lab
spec:
  type: NodePort
  selector:
    app: activity-service
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: mls-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: activity-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082